### PR TITLE
fix(pages): create new entry

### LINKED ISSUE #12: [pages] Ability to create new entries

### PR DESCRIPTION
**Pull request by heafalan**
Fixes #12

### CODE REVIEW

File: packages/pages/src/App.js [hunk 1]
```diff
@@ -4,18 +4,49 @@ import { format, parse } from "json-rpc-protocol";
...
+      </button>
+    </div>
   </div>
 );
 
 export default provideState({
   initialState: () => ({
     entries: [],
+    name: "name",
+    content: "content",
```
Comment (julien-f) [inline packages/pages/src/App.js]: These values should probably be empty initially.

File: packages/pages/src/App.js [hunk 2]
```diff
@@ -25,5 +56,30 @@ export default provideState({
...
     },
+    async createEntry() {
+      await fetch("/api/", {
+        method: "post",
+        body: format.request(0, "createEntry", {
+          name: this.state.name,
+          content: this.state.content,
+        }),
+      });
+    },
```
Comment (julien-f) [inline packages/pages/src/App.js:71]: IMHO, `name` and `content` should be reset after creating an entry.

**Review by julien-f — APPROVED** [review]

**Comment by julien-f** [comment]
Please add `Fixes #<issue number>` in your PR.
